export type FoodCategory =
  | 'breakfast'
  | 'lunch'
  | 'dinner'
  | 'snack'
  | 'protein'
  | 'dairy'
  | 'fruit'
  | 'vegetable'
  | 'beverage'
  | 'sweet';

export type FoodEntry = {
  id: string;
  name: string;
  aliases: string[];
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  fiber: number;
  serving_size: string;
  serving_grams: number;
  category: FoodCategory;
  tags: string[];
};

export const foodDatabase: FoodEntry[] = [
  { id: 'idli', name: 'idli', aliases: ['idly', 'idlee'], calories: 39, protein: 2, carbs: 8, fats: 0.4, fiber: 0.5, serving_size: '1 piece', serving_grams: 35, category: 'breakfast', tags: ['south indian', 'steamed'] },
  { id: 'dosa-plain', name: 'dosa plain', aliases: ['dose', 'dosai'], calories: 120, protein: 3, carbs: 22, fats: 2, fiber: 0.8, serving_size: '1 piece', serving_grams: 90, category: 'breakfast', tags: ['south indian'] },
  { id: 'masala-dosa', name: 'masala dosa', aliases: [], calories: 230, protein: 5, carbs: 38, fats: 6, fiber: 2, serving_size: '1 piece', serving_grams: 180, category: 'breakfast', tags: ['south indian', 'potato'] },
  { id: 'rava-dosa', name: 'rava dosa', aliases: ['suji dosa'], calories: 150, protein: 3, carbs: 24, fats: 4, fiber: 0.5, serving_size: '1 piece', serving_grams: 100, category: 'breakfast', tags: ['south indian'] },
  { id: 'uttapam', name: 'uttapam', aliases: [], calories: 180, protein: 5, carbs: 30, fats: 4, fiber: 1.5, serving_size: '1 piece', serving_grams: 140, category: 'breakfast', tags: ['south indian'] },
  { id: 'poha', name: 'poha', aliases: ['aval', 'chivda', 'flattened rice'], calories: 180, protein: 3, carbs: 35, fats: 3, fiber: 1.5, serving_size: '1 cup', serving_grams: 150, category: 'breakfast', tags: ['light'] },
  { id: 'upma', name: 'upma', aliases: [], calories: 190, protein: 4, carbs: 32, fats: 5, fiber: 2, serving_size: '1 cup', serving_grams: 170, category: 'breakfast', tags: ['semolina'] },
  { id: 'rava-upma', name: 'rava upma', aliases: ['suji upma'], calories: 200, protein: 4, carbs: 34, fats: 5, fiber: 1.5, serving_size: '1 cup', serving_grams: 170, category: 'breakfast', tags: ['semolina'] },
  { id: 'aloo-paratha', name: 'aloo paratha', aliases: [], calories: 250, protein: 6, carbs: 38, fats: 8, fiber: 2.5, serving_size: '1 piece', serving_grams: 120, category: 'breakfast', tags: ['north indian'] },
  { id: 'plain-paratha', name: 'plain paratha', aliases: [], calories: 180, protein: 4, carbs: 28, fats: 6, fiber: 2, serving_size: '1 piece', serving_grams: 90, category: 'breakfast', tags: ['north indian'] },
  { id: 'methi-paratha', name: 'methi paratha', aliases: [], calories: 190, protein: 5, carbs: 28, fats: 6, fiber: 3, serving_size: '1 piece', serving_grams: 100, category: 'breakfast', tags: ['north indian'] },
  { id: 'gobi-paratha', name: 'gobi paratha', aliases: [], calories: 220, protein: 5, carbs: 32, fats: 8, fiber: 2.5, serving_size: '1 piece', serving_grams: 110, category: 'breakfast', tags: ['north indian'] },
  { id: 'paneer-paratha', name: 'paneer paratha', aliases: [], calories: 280, protein: 10, carbs: 32, fats: 12, fiber: 2, serving_size: '1 piece', serving_grams: 120, category: 'breakfast', tags: ['north indian', 'high protein'] },
  { id: 'roti', name: 'roti', aliases: ['chapati', 'chapathi', 'phulka', 'wheat roti'], calories: 80, protein: 3, carbs: 15, fats: 1, fiber: 1.5, serving_size: '1 piece', serving_grams: 30, category: 'breakfast', tags: ['indian bread'] },
  { id: 'missi-roti', name: 'missi roti', aliases: [], calories: 100, protein: 4, carbs: 16, fats: 2, fiber: 2.5, serving_size: '1 piece', serving_grams: 40, category: 'breakfast', tags: ['indian bread'] },
  { id: 'puri', name: 'puri', aliases: [], calories: 110, protein: 2, carbs: 14, fats: 5, fiber: 1, serving_size: '1 piece', serving_grams: 25, category: 'breakfast', tags: ['fried'] },
  { id: 'bhatura', name: 'bhatura', aliases: [], calories: 200, protein: 5, carbs: 30, fats: 7, fiber: 1.5, serving_size: '1 piece', serving_grams: 90, category: 'breakfast', tags: ['fried'] },
  { id: 'appam', name: 'appam', aliases: [], calories: 80, protein: 2, carbs: 16, fats: 0.5, fiber: 0.8, serving_size: '1 piece', serving_grams: 55, category: 'breakfast', tags: ['south indian'] },
  { id: 'puttu', name: 'puttu', aliases: [], calories: 180, protein: 4, carbs: 38, fats: 1, fiber: 2, serving_size: '1 cup', serving_grams: 150, category: 'breakfast', tags: ['kerala'] },
  { id: 'pesarattu', name: 'pesarattu', aliases: [], calories: 140, protein: 6, carbs: 22, fats: 3, fiber: 2.5, serving_size: '1 piece', serving_grams: 90, category: 'breakfast', tags: ['south indian'] },
  { id: 'idiyappam', name: 'idiyappam', aliases: ['string hoppers', 'noolputtu'], calories: 120, protein: 2, carbs: 25, fats: 0.5, fiber: 1, serving_size: '1 serving', serving_grams: 100, category: 'breakfast', tags: ['south indian'] },
  { id: 'bread-white', name: 'bread white', aliases: [], calories: 70, protein: 2, carbs: 13, fats: 1, fiber: 0.8, serving_size: '1 slice', serving_grams: 25, category: 'breakfast', tags: ['bakery'] },
  { id: 'bread-brown', name: 'bread brown', aliases: [], calories: 65, protein: 3, carbs: 12, fats: 1, fiber: 2, serving_size: '1 slice', serving_grams: 25, category: 'breakfast', tags: ['bakery'] },
  { id: 'bread-omelette', name: 'bread omelette', aliases: [], calories: 280, protein: 14, carbs: 26, fats: 12, fiber: 1.5, serving_size: '1 serving', serving_grams: 160, category: 'breakfast', tags: ['eggs'] },
  { id: 'oats-cooked', name: 'oats cooked', aliases: ['oatmeal', 'quaker oats'], calories: 150, protein: 5, carbs: 27, fats: 3, fiber: 4, serving_size: '1 cup', serving_grams: 234, category: 'breakfast', tags: ['whole grain'] },
  { id: 'cornflakes', name: 'cornflakes', aliases: ['kelloggs'], calories: 150, protein: 2, carbs: 35, fats: 0.5, fiber: 1, serving_size: '1 cup', serving_grams: 30, category: 'breakfast', tags: ['cereal'] },
  { id: 'muesli', name: 'muesli', aliases: [], calories: 300, protein: 8, carbs: 55, fats: 6, fiber: 4, serving_size: '1 cup', serving_grams: 85, category: 'breakfast', tags: ['cereal'] },
  { id: 'dalia-cooked', name: 'dalia cooked', aliases: ['broken wheat', 'daliya'], calories: 150, protein: 5, carbs: 30, fats: 1, fiber: 3.5, serving_size: '1 cup', serving_grams: 170, category: 'breakfast', tags: ['whole grain'] },
  { id: 'ragi-porridge', name: 'ragi porridge', aliases: ['finger millet', 'nachni'], calories: 160, protein: 3, carbs: 34, fats: 1, fiber: 3.6, serving_size: '1 cup', serving_grams: 200, category: 'breakfast', tags: ['millet'] },
  { id: 'sattu-drink', name: 'sattu drink', aliases: [], calories: 120, protein: 7, carbs: 20, fats: 1, fiber: 8, serving_size: '1 glass', serving_grams: 250, category: 'beverage', tags: ['high fiber'] },
  { id: 'boiled-egg', name: 'boiled egg', aliases: ['anda', 'unda', 'egg', 'boiled anda'], calories: 78, protein: 6, carbs: 0.6, fats: 5, fiber: 0, serving_size: '1 egg', serving_grams: 50, category: 'protein', tags: ['eggs'] },
  { id: 'egg-white', name: 'egg white', aliases: [], calories: 17, protein: 4, carbs: 0.2, fats: 0, fiber: 0, serving_size: '1 egg', serving_grams: 33, category: 'protein', tags: ['eggs'] },
  { id: 'egg-yolk', name: 'egg yolk', aliases: [], calories: 61, protein: 3, carbs: 0.3, fats: 5, fiber: 0, serving_size: '1 yolk', serving_grams: 17, category: 'protein', tags: ['eggs'] },
  { id: 'scrambled-eggs', name: 'scrambled eggs', aliases: ['anda bhurji'], calories: 200, protein: 14, carbs: 2, fats: 15, fiber: 0, serving_size: '2 eggs', serving_grams: 120, category: 'protein', tags: ['eggs'] },
  { id: 'omelette-plain', name: 'omelette plain', aliases: [], calories: 190, protein: 13, carbs: 1, fats: 14, fiber: 0, serving_size: '2 eggs', serving_grams: 110, category: 'protein', tags: ['eggs'] },
  { id: 'omelette-masala', name: 'omelette masala', aliases: [], calories: 220, protein: 14, carbs: 4, fats: 16, fiber: 0.5, serving_size: '2 eggs', serving_grams: 130, category: 'protein', tags: ['eggs'] },
  { id: 'egg-bhurji', name: 'egg bhurji', aliases: ['anda bhurji'], calories: 230, protein: 14, carbs: 5, fats: 17, fiber: 0.5, serving_size: '2 eggs', serving_grams: 130, category: 'protein', tags: ['eggs'] },
  { id: 'poached-egg', name: 'poached egg', aliases: [], calories: 72, protein: 6, carbs: 0.4, fats: 5, fiber: 0, serving_size: '1 egg', serving_grams: 50, category: 'protein', tags: ['eggs'] },
  { id: 'egg-curry', name: 'egg curry', aliases: ['anda curry', 'egg masala'], calories: 250, protein: 14, carbs: 8, fats: 18, fiber: 1, serving_size: '1 serving', serving_grams: 180, category: 'lunch', tags: ['eggs', 'curry'] },
  { id: 'white-rice-cooked', name: 'white rice cooked', aliases: ['chawal', 'rice', 'steamed rice'], calories: 200, protein: 4, carbs: 44, fats: 0.4, fiber: 0.6, serving_size: '1 cup', serving_grams: 158, category: 'lunch', tags: ['rice'] },
  { id: 'brown-rice-cooked', name: 'brown rice cooked', aliases: [], calories: 215, protein: 5, carbs: 45, fats: 2, fiber: 3.5, serving_size: '1 cup', serving_grams: 195, category: 'lunch', tags: ['rice'] },
  { id: 'basmati-rice-cooked', name: 'basmati rice cooked', aliases: [], calories: 210, protein: 4, carbs: 46, fats: 0.5, fiber: 0.7, serving_size: '1 cup', serving_grams: 160, category: 'lunch', tags: ['rice'] },
  { id: 'jeera-rice', name: 'jeera rice', aliases: ['cumin rice'], calories: 250, protein: 4, carbs: 46, fats: 5, fiber: 0.8, serving_size: '1 cup', serving_grams: 180, category: 'lunch', tags: ['rice'] },
  { id: 'pulao-veg', name: 'pulao veg', aliases: [], calories: 280, protein: 6, carbs: 48, fats: 7, fiber: 2, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['rice'] },
  { id: 'chicken-pulao', name: 'chicken pulao', aliases: [], calories: 350, protein: 18, carbs: 46, fats: 9, fiber: 1.5, serving_size: '1 cup', serving_grams: 220, category: 'lunch', tags: ['rice', 'chicken'] },
  { id: 'veg-biryani', name: 'veg biryani', aliases: [], calories: 300, protein: 7, carbs: 50, fats: 8, fiber: 3, serving_size: '1 cup', serving_grams: 220, category: 'lunch', tags: ['rice'] },
  { id: 'chicken-biryani', name: 'chicken biryani', aliases: [], calories: 400, protein: 22, carbs: 50, fats: 12, fiber: 2, serving_size: '1 cup', serving_grams: 250, category: 'lunch', tags: ['rice', 'chicken'] },
  { id: 'mutton-biryani', name: 'mutton biryani', aliases: [], calories: 450, protein: 24, carbs: 50, fats: 15, fiber: 2, serving_size: '1 cup', serving_grams: 250, category: 'dinner', tags: ['rice', 'mutton'] },
  { id: 'khichdi', name: 'khichdi', aliases: [], calories: 200, protein: 8, carbs: 36, fats: 3, fiber: 3, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['rice', 'dal'] },
  { id: 'curd-rice', name: 'curd rice', aliases: ['thayir sadam', 'dahi chawal'], calories: 220, protein: 7, carbs: 38, fats: 4, fiber: 0.8, serving_size: '1 cup', serving_grams: 220, category: 'lunch', tags: ['rice', 'dairy'] },
  { id: 'lemon-rice', name: 'lemon rice', aliases: ['chitranna'], calories: 240, protein: 4, carbs: 44, fats: 5, fiber: 1, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['rice'] },
  { id: 'tamarind-rice', name: 'tamarind rice', aliases: ['puliyogare', 'pulihora'], calories: 260, protein: 4, carbs: 46, fats: 6, fiber: 1.5, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['rice'] },
  { id: 'bisi-bele-bath', name: 'bisi bele bath', aliases: [], calories: 280, protein: 9, carbs: 46, fats: 6, fiber: 4, serving_size: '1 cup', serving_grams: 230, category: 'lunch', tags: ['rice', 'dal'] },
  { id: 'pongal', name: 'pongal', aliases: ['ven pongal'], calories: 260, protein: 7, carbs: 44, fats: 6, fiber: 2, serving_size: '1 cup', serving_grams: 220, category: 'breakfast', tags: ['rice'] },
  { id: 'quinoa-cooked', name: 'quinoa cooked', aliases: [], calories: 220, protein: 8, carbs: 39, fats: 4, fiber: 5, serving_size: '1 cup', serving_grams: 185, category: 'lunch', tags: ['grain'] },
  { id: 'toor-dal-cooked', name: 'toor dal cooked', aliases: ['arhar dal', 'pigeon peas', 'sambar dal'], calories: 200, protein: 14, carbs: 34, fats: 1, fiber: 7, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['dal'] },
  { id: 'moong-dal-cooked', name: 'moong dal cooked', aliases: ['green gram dal', 'yellow moong'], calories: 180, protein: 14, carbs: 30, fats: 1, fiber: 7, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['dal'] },
  { id: 'masoor-dal-cooked', name: 'masoor dal cooked', aliases: ['red lentil', 'pink dal'], calories: 190, protein: 18, carbs: 34, fats: 1, fiber: 8, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['dal'] },
  { id: 'chana-dal-cooked', name: 'chana dal cooked', aliases: [], calories: 270, protein: 15, carbs: 45, fats: 5, fiber: 8, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['dal'] },
  { id: 'urad-dal-cooked', name: 'urad dal cooked', aliases: ['black gram dal', 'white dal'], calories: 210, protein: 15, carbs: 35, fats: 1, fiber: 6, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['dal'] },
  { id: 'dal-makhani', name: 'dal makhani', aliases: [], calories: 280, protein: 12, carbs: 32, fats: 12, fiber: 8, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['dal'] },
  { id: 'rajma-cooked', name: 'rajma cooked', aliases: ['kidney beans', 'rajma chawal'], calories: 270, protein: 17, carbs: 45, fats: 1, fiber: 9, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['legume'] },
  { id: 'chana-cooked', name: 'chana cooked', aliases: ['chickpeas', 'chole', 'kabuli chana'], calories: 270, protein: 15, carbs: 45, fats: 4, fiber: 9, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['legume'] },
  { id: 'moong-whole-cooked', name: 'moong whole cooked', aliases: ['whole moong', 'green moong'], calories: 210, protein: 14, carbs: 36, fats: 1, fiber: 8, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['legume'] },
  { id: 'lobia-cooked', name: 'lobia cooked', aliases: ['black eyed peas', 'chawli'], calories: 200, protein: 13, carbs: 36, fats: 1, fiber: 8, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['legume'] },
  { id: 'soya-chunks-cooked', name: 'soya chunks cooked', aliases: ['meal maker', 'nutrela'], calories: 280, protein: 36, carbs: 24, fats: 1, fiber: 4, serving_size: '1 cup', serving_grams: 100, category: 'protein', tags: ['soy'] },
  { id: 'sambar', name: 'sambar', aliases: [], calories: 130, protein: 6, carbs: 18, fats: 4, fiber: 3, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['dal', 'south indian'] },
  { id: 'rasam', name: 'rasam', aliases: [], calories: 60, protein: 2, carbs: 8, fats: 2, fiber: 1, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['south indian'] },
  { id: 'palak-cooked', name: 'palak cooked', aliases: ['spinach', 'saag'], calories: 60, protein: 5, carbs: 7, fats: 2, fiber: 2.5, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['greens'] },
  { id: 'methi-cooked', name: 'methi cooked', aliases: ['fenugreek leaves'], calories: 70, protein: 5, carbs: 9, fats: 2, fiber: 3, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['greens'] },
  { id: 'aloo-gobi', name: 'aloo gobi', aliases: ['potato cauliflower'], calories: 180, protein: 4, carbs: 28, fats: 6, fiber: 3, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['sabzi'] },
  { id: 'aloo-sabzi', name: 'aloo sabzi', aliases: ['potato curry', 'aloo curry'], calories: 200, protein: 3, carbs: 30, fats: 7, fiber: 2.5, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['sabzi'] },
  { id: 'bhindi-masala', name: 'bhindi masala', aliases: ['okra', 'ladies finger'], calories: 150, protein: 3, carbs: 18, fats: 7, fiber: 3.5, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['sabzi'] },
  { id: 'baingan-bharta', name: 'baingan bharta', aliases: ['brinjal', 'eggplant'], calories: 140, protein: 3, carbs: 16, fats: 7, fiber: 2.5, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['sabzi'] },
  { id: 'mix-veg-curry', name: 'mix veg curry', aliases: [], calories: 160, protein: 4, carbs: 20, fats: 7, fiber: 3, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['sabzi'] },
  { id: 'paneer-bhurji', name: 'paneer bhurji', aliases: [], calories: 280, protein: 16, carbs: 8, fats: 20, fiber: 0.5, serving_size: '1 cup', serving_grams: 180, category: 'protein', tags: ['paneer'] },
  { id: 'palak-paneer', name: 'palak paneer', aliases: [], calories: 300, protein: 16, carbs: 12, fats: 22, fiber: 2.5, serving_size: '1 cup', serving_grams: 200, category: 'dinner', tags: ['paneer'] },
  { id: 'paneer-butter-masala', name: 'paneer butter masala', aliases: [], calories: 380, protein: 18, carbs: 16, fats: 28, fiber: 1.5, serving_size: '1 cup', serving_grams: 200, category: 'dinner', tags: ['paneer'] },
  { id: 'shahi-paneer', name: 'shahi paneer', aliases: [], calories: 400, protein: 18, carbs: 18, fats: 30, fiber: 1, serving_size: '1 cup', serving_grams: 200, category: 'dinner', tags: ['paneer'] },
  { id: 'matar-paneer', name: 'matar paneer', aliases: [], calories: 320, protein: 16, carbs: 20, fats: 20, fiber: 4, serving_size: '1 cup', serving_grams: 200, category: 'dinner', tags: ['paneer'] },
  { id: 'kadhi', name: 'kadhi', aliases: [], calories: 160, protein: 5, carbs: 18, fats: 8, fiber: 0.5, serving_size: '1 cup', serving_grams: 200, category: 'lunch', tags: ['dairy'] },
  { id: 'kadhi-pakora', name: 'kadhi pakora', aliases: [], calories: 240, protein: 7, carbs: 24, fats: 12, fiber: 1, serving_size: '1 cup', serving_grams: 220, category: 'lunch', tags: ['dairy', 'fried'] },
  { id: 'sarson-da-saag', name: 'sarson da saag', aliases: [], calories: 180, protein: 7, carbs: 18, fats: 9, fiber: 5, serving_size: '1 cup', serving_grams: 180, category: 'vegetable', tags: ['greens'] },
  { id: 'undhiyu', name: 'undhiyu', aliases: [], calories: 220, protein: 7, carbs: 28, fats: 10, fiber: 5, serving_size: '1 cup', serving_grams: 200, category: 'vegetable', tags: ['gujarati'] },
  { id: 'avial', name: 'avial', aliases: [], calories: 180, protein: 4, carbs: 20, fats: 10, fiber: 4, serving_size: '1 cup', serving_grams: 200, category: 'vegetable', tags: ['kerala'] },
  { id: 'chicken-breast-grilled', name: 'chicken breast grilled', aliases: ['grilled chicken'], calories: 165, protein: 31, carbs: 0, fats: 4, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-breast-boiled', name: 'chicken breast boiled', aliases: ['boiled chicken'], calories: 150, protein: 30, carbs: 0, fats: 3, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-thigh', name: 'chicken thigh', aliases: [], calories: 210, protein: 26, carbs: 0, fats: 12, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-drumstick', name: 'chicken drumstick', aliases: ['chicken leg'], calories: 190, protein: 24, carbs: 0, fats: 10, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-curry', name: 'chicken curry', aliases: [], calories: 280, protein: 25, carbs: 8, fats: 16, fiber: 1, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['chicken', 'curry'] },
  { id: 'butter-chicken', name: 'butter chicken', aliases: ['murgh makhani'], calories: 350, protein: 28, carbs: 12, fats: 22, fiber: 1, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['chicken', 'curry'] },
  { id: 'chicken-tikka', name: 'chicken tikka', aliases: [], calories: 200, protein: 28, carbs: 4, fats: 8, fiber: 0.5, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'tandoori-chicken', name: 'tandoori chicken', aliases: [], calories: 180, protein: 28, carbs: 3, fats: 6, fiber: 0.5, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-keema', name: 'chicken keema', aliases: ['minced chicken'], calories: 220, protein: 24, carbs: 4, fats: 12, fiber: 0.5, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-seekh-kebab', name: 'chicken seekh kebab', aliases: [], calories: 120, protein: 14, carbs: 3, fats: 6, fiber: 0.3, serving_size: '1 piece', serving_grams: 60, category: 'protein', tags: ['chicken'] },
  { id: 'chicken-65', name: 'chicken 65', aliases: [], calories: 250, protein: 22, carbs: 8, fats: 14, fiber: 0.5, serving_size: '100g', serving_grams: 100, category: 'snack', tags: ['chicken', 'fried'] },
  { id: 'chicken-lollipop', name: 'chicken lollipop', aliases: [], calories: 200, protein: 16, carbs: 6, fats: 12, fiber: 0.3, serving_size: '2 pieces', serving_grams: 120, category: 'snack', tags: ['chicken', 'fried'] },
  { id: 'chettinad-chicken', name: 'chettinad chicken', aliases: [], calories: 320, protein: 26, carbs: 8, fats: 20, fiber: 1, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['chicken', 'curry'] },
  { id: 'mutton-curry', name: 'mutton curry', aliases: [], calories: 320, protein: 26, carbs: 6, fats: 20, fiber: 0.5, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['mutton', 'curry'] },
  { id: 'mutton-rogan-josh', name: 'mutton rogan josh', aliases: [], calories: 340, protein: 28, carbs: 8, fats: 22, fiber: 0.5, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['mutton', 'curry'] },
  { id: 'mutton-keema', name: 'mutton keema', aliases: [], calories: 250, protein: 22, carbs: 4, fats: 16, fiber: 0.3, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['mutton'] },
  { id: 'fish-curry', name: 'fish curry', aliases: [], calories: 200, protein: 22, carbs: 6, fats: 10, fiber: 0.5, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['fish', 'curry'] },
  { id: 'fish-fry', name: 'fish fry', aliases: [], calories: 220, protein: 24, carbs: 4, fats: 12, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['fish', 'fried'] },
  { id: 'prawn-curry', name: 'prawn curry', aliases: [], calories: 220, protein: 24, carbs: 6, fats: 10, fiber: 0.5, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['seafood', 'curry'] },
  { id: 'fish-rohu', name: 'fish rohu', aliases: [], calories: 100, protein: 16, carbs: 0, fats: 4, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['fish'] },
  { id: 'fish-pomfret', name: 'fish pomfret', aliases: [], calories: 95, protein: 18, carbs: 0, fats: 3, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['fish'] },
  { id: 'salmon', name: 'salmon', aliases: [], calories: 208, protein: 20, carbs: 0, fats: 13, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['fish'] },
  { id: 'tuna-canned', name: 'tuna canned', aliases: [], calories: 130, protein: 28, carbs: 0, fats: 1, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['fish'] },
  { id: 'prawn-grilled', name: 'prawn grilled', aliases: ['shrimp'], calories: 120, protein: 24, carbs: 1, fats: 2, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['seafood'] },
  { id: 'crab-curry', name: 'crab curry', aliases: [], calories: 200, protein: 22, carbs: 6, fats: 10, fiber: 0.5, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['seafood', 'curry'] },
  { id: 'kerala-fish-curry', name: 'kerala fish curry', aliases: [], calories: 220, protein: 22, carbs: 6, fats: 12, fiber: 1, serving_size: '1 cup', serving_grams: 220, category: 'dinner', tags: ['fish', 'kerala'] },
  { id: 'full-fat-milk', name: 'full fat milk', aliases: ['doodh', 'whole milk'], calories: 130, protein: 7, carbs: 10, fats: 7, fiber: 0, serving_size: '200ml', serving_grams: 200, category: 'dairy', tags: ['milk'] },
  { id: 'toned-milk', name: 'toned milk', aliases: [], calories: 100, protein: 7, carbs: 10, fats: 3, fiber: 0, serving_size: '200ml', serving_grams: 200, category: 'dairy', tags: ['milk'] },
  { id: 'skimmed-milk', name: 'skimmed milk', aliases: [], calories: 70, protein: 7, carbs: 10, fats: 0.5, fiber: 0, serving_size: '200ml', serving_grams: 200, category: 'dairy', tags: ['milk'] },
  { id: 'curd-full-fat', name: 'curd full fat', aliases: ['dahi', 'yogurt', 'curd'], calories: 150, protein: 8, carbs: 12, fats: 8, fiber: 0, serving_size: '1 cup', serving_grams: 200, category: 'dairy', tags: ['curd'] },
  { id: 'curd-low-fat', name: 'curd low fat', aliases: [], calories: 100, protein: 8, carbs: 12, fats: 2, fiber: 0, serving_size: '1 cup', serving_grams: 200, category: 'dairy', tags: ['curd'] },
  { id: 'greek-yogurt', name: 'greek yogurt', aliases: [], calories: 130, protein: 17, carbs: 9, fats: 0.5, fiber: 0, serving_size: '1 cup', serving_grams: 200, category: 'dairy', tags: ['curd'] },
  { id: 'paneer', name: 'paneer', aliases: ['cottage cheese', 'chenna'], calories: 265, protein: 18, carbs: 3, fats: 20, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['dairy'] },
  { id: 'ghee', name: 'ghee', aliases: ['clarified butter'], calories: 45, protein: 0, carbs: 0, fats: 5, fiber: 0, serving_size: '1 tsp', serving_grams: 5, category: 'dairy', tags: ['fat'] },
  { id: 'butter', name: 'butter', aliases: ['makhan', 'makkhan'], calories: 36, protein: 0, carbs: 0, fats: 4, fiber: 0, serving_size: '1 tsp', serving_grams: 5, category: 'dairy', tags: ['fat'] },
  { id: 'cheese-slice', name: 'cheese slice', aliases: [], calories: 70, protein: 4, carbs: 1, fats: 6, fiber: 0, serving_size: '1 slice', serving_grams: 20, category: 'dairy', tags: ['cheese'] },
  { id: 'mozzarella', name: 'mozzarella', aliases: [], calories: 80, protein: 6, carbs: 1, fats: 6, fiber: 0, serving_size: '30g', serving_grams: 30, category: 'dairy', tags: ['cheese'] },
  { id: 'lassi-sweet', name: 'lassi sweet', aliases: [], calories: 180, protein: 6, carbs: 28, fats: 5, fiber: 0, serving_size: '1 glass', serving_grams: 250, category: 'beverage', tags: ['dairy'] },
  { id: 'lassi-salted', name: 'lassi salted', aliases: [], calories: 100, protein: 6, carbs: 12, fats: 4, fiber: 0, serving_size: '1 glass', serving_grams: 250, category: 'beverage', tags: ['dairy'] },
  { id: 'chaach', name: 'chaach', aliases: ['buttermilk', 'mattha'], calories: 60, protein: 3, carbs: 6, fats: 2, fiber: 0, serving_size: '1 glass', serving_grams: 250, category: 'beverage', tags: ['dairy'] },
  { id: 'khoya', name: 'khoya', aliases: ['mawa', 'khoa'], calories: 180, protein: 7, carbs: 20, fats: 9, fiber: 0, serving_size: '50g', serving_grams: 50, category: 'dairy', tags: ['dessert ingredient'] },
  { id: 'condensed-milk', name: 'condensed milk', aliases: ['milkmaid'], calories: 165, protein: 4, carbs: 28, fats: 4, fiber: 0, serving_size: '50g', serving_grams: 50, category: 'dairy', tags: ['dessert ingredient'] },
  { id: 'haldi-doodh', name: 'haldi doodh', aliases: ['turmeric milk', 'golden milk'], calories: 140, protein: 7, carbs: 11, fats: 7, fiber: 0, serving_size: '1 cup', serving_grams: 240, category: 'beverage', tags: ['dairy'] },
  { id: 'samosa', name: 'samosa', aliases: [], calories: 130, protein: 3, carbs: 16, fats: 6, fiber: 1.5, serving_size: '1 piece', serving_grams: 60, category: 'snack', tags: ['street food'] },
  { id: 'vada-pav', name: 'vada pav', aliases: [], calories: 290, protein: 6, carbs: 44, fats: 10, fiber: 2, serving_size: '1', serving_grams: 140, category: 'snack', tags: ['street food'] },
  { id: 'pav-bhaji', name: 'pav bhaji', aliases: [], calories: 350, protein: 9, carbs: 52, fats: 12, fiber: 4, serving_size: '1 serving', serving_grams: 300, category: 'lunch', tags: ['street food'] },
  { id: 'chole-bhature', name: 'chole bhature', aliases: [], calories: 600, protein: 18, carbs: 80, fats: 22, fiber: 7, serving_size: '1 serving', serving_grams: 350, category: 'lunch', tags: ['street food'] },
  { id: 'misal-pav', name: 'misal pav', aliases: [], calories: 380, protein: 14, carbs: 58, fats: 10, fiber: 6, serving_size: '1 serving', serving_grams: 300, category: 'snack', tags: ['street food'] },
  { id: 'dhokla', name: 'dhokla', aliases: [], calories: 150, protein: 6, carbs: 24, fats: 4, fiber: 1, serving_size: '2 pieces', serving_grams: 80, category: 'snack', tags: ['street food'] },
  { id: 'medu-vada', name: 'medu vada', aliases: ['urad vada', 'wada'], calories: 130, protein: 4, carbs: 18, fats: 5, fiber: 1.5, serving_size: '1 piece', serving_grams: 50, category: 'snack', tags: ['street food'] },
  { id: 'pani-puri', name: 'pani puri', aliases: ['golgappa', 'puchka', 'phuchka'], calories: 200, protein: 4, carbs: 34, fats: 5, fiber: 2, serving_size: '6 pieces', serving_grams: 150, category: 'snack', tags: ['street food'] },
  { id: 'bhel-puri', name: 'bhel puri', aliases: [], calories: 180, protein: 4, carbs: 32, fats: 4, fiber: 3, serving_size: '1 cup', serving_grams: 120, category: 'snack', tags: ['street food'] },
  { id: 'sev-puri', name: 'sev puri', aliases: [], calories: 220, protein: 5, carbs: 36, fats: 6, fiber: 2, serving_size: '1 serving', serving_grams: 140, category: 'snack', tags: ['street food'] },
  { id: 'dahi-puri', name: 'dahi puri', aliases: [], calories: 240, protein: 7, carbs: 38, fats: 6, fiber: 2, serving_size: '1 serving', serving_grams: 160, category: 'snack', tags: ['street food'] },
  { id: 'momos-steamed-veg', name: 'momos steamed veg', aliases: ['dim sum', 'dumpling'], calories: 180, protein: 6, carbs: 28, fats: 4, fiber: 1.5, serving_size: '6', serving_grams: 180, category: 'snack', tags: ['street food'] },
  { id: 'momos-steamed-chicken', name: 'momos steamed chicken', aliases: [], calories: 200, protein: 12, carbs: 26, fats: 4, fiber: 1, serving_size: '6', serving_grams: 180, category: 'snack', tags: ['street food'] },
  { id: 'momos-fried', name: 'momos fried', aliases: [], calories: 280, protein: 8, carbs: 28, fats: 14, fiber: 1.5, serving_size: '6', serving_grams: 180, category: 'snack', tags: ['street food', 'fried'] },
  { id: 'spring-roll', name: 'spring roll', aliases: [], calories: 200, protein: 5, carbs: 28, fats: 8, fiber: 1.5, serving_size: '2', serving_grams: 100, category: 'snack', tags: ['street food'] },
  { id: 'bread-pakora', name: 'bread pakora', aliases: [], calories: 180, protein: 5, carbs: 24, fats: 7, fiber: 1.5, serving_size: '1', serving_grams: 90, category: 'snack', tags: ['street food', 'fried'] },
  { id: 'aloo-tikki', name: 'aloo tikki', aliases: [], calories: 150, protein: 3, carbs: 22, fats: 6, fiber: 2, serving_size: '1', serving_grams: 70, category: 'snack', tags: ['street food'] },
  { id: 'dahi-vada', name: 'dahi vada', aliases: ['dahi bhalla'], calories: 200, protein: 8, carbs: 28, fats: 7, fiber: 1.5, serving_size: '2', serving_grams: 170, category: 'snack', tags: ['street food'] },
  { id: 'kachori', name: 'kachori', aliases: [], calories: 180, protein: 4, carbs: 22, fats: 9, fiber: 2, serving_size: '1', serving_grams: 65, category: 'snack', tags: ['street food', 'fried'] },
  { id: 'litti-chokha', name: 'litti chokha', aliases: [], calories: 400, protein: 12, carbs: 56, fats: 14, fiber: 5, serving_size: '2 litti', serving_grams: 220, category: 'lunch', tags: ['bihari'] },
  { id: 'burger-chicken', name: 'burger chicken', aliases: [], calories: 420, protein: 22, carbs: 42, fats: 18, fiber: 2, serving_size: '1', serving_grams: 220, category: 'snack', tags: ['fast food'] },
  { id: 'burger-veg', name: 'burger veg', aliases: [], calories: 320, protein: 10, carbs: 42, fats: 12, fiber: 3, serving_size: '1', serving_grams: 200, category: 'snack', tags: ['fast food'] },
  { id: 'burger-egg', name: 'burger egg', aliases: [], calories: 350, protein: 16, carbs: 38, fats: 16, fiber: 1.5, serving_size: '1', serving_grams: 210, category: 'snack', tags: ['fast food'] },
  { id: 'pizza-margherita-slice', name: 'pizza margherita slice', aliases: [], calories: 250, protein: 10, carbs: 32, fats: 10, fiber: 2, serving_size: '1', serving_grams: 100, category: 'snack', tags: ['fast food'] },
  { id: 'pizza-cheese-slice', name: 'pizza cheese slice', aliases: [], calories: 280, protein: 12, carbs: 32, fats: 12, fiber: 2, serving_size: '1', serving_grams: 100, category: 'snack', tags: ['fast food'] },
  { id: 'french-fries', name: 'french fries', aliases: [], calories: 320, protein: 4, carbs: 42, fats: 15, fiber: 3, serving_size: '1 serving', serving_grams: 120, category: 'snack', tags: ['fast food'] },
  { id: 'sandwich-chicken', name: 'sandwich chicken', aliases: [], calories: 380, protein: 24, carbs: 40, fats: 14, fiber: 2.5, serving_size: '1', serving_grams: 220, category: 'snack', tags: ['fast food'] },
  { id: 'sandwich-veg', name: 'sandwich veg', aliases: [], calories: 280, protein: 10, carbs: 40, fats: 8, fiber: 3, serving_size: '1', serving_grams: 200, category: 'snack', tags: ['fast food'] },
  { id: 'wrap-chicken', name: 'wrap chicken', aliases: [], calories: 350, protein: 22, carbs: 38, fats: 12, fiber: 2, serving_size: '1', serving_grams: 220, category: 'snack', tags: ['fast food'] },
  { id: 'wrap-paneer', name: 'wrap paneer', aliases: [], calories: 320, protein: 14, carbs: 40, fats: 12, fiber: 2.5, serving_size: '1', serving_grams: 220, category: 'snack', tags: ['fast food'] },
  { id: 'pasta-arrabiata', name: 'pasta arrabiata', aliases: [], calories: 280, protein: 8, carbs: 50, fats: 6, fiber: 3, serving_size: '1 cup', serving_grams: 200, category: 'snack', tags: ['fast food'] },
  { id: 'pasta-carbonara', name: 'pasta carbonara', aliases: [], calories: 380, protein: 14, carbs: 50, fats: 16, fiber: 2, serving_size: '1 cup', serving_grams: 220, category: 'snack', tags: ['fast food'] },
  { id: 'noodles-veg', name: 'noodles veg', aliases: [], calories: 250, protein: 6, carbs: 42, fats: 6, fiber: 2, serving_size: '1 cup', serving_grams: 180, category: 'snack', tags: ['fast food'] },
  { id: 'noodles-chicken', name: 'noodles chicken', aliases: [], calories: 300, protein: 16, carbs: 40, fats: 8, fiber: 2, serving_size: '1 cup', serving_grams: 200, category: 'snack', tags: ['fast food'] },
  { id: 'hakka-noodles', name: 'hakka noodles', aliases: [], calories: 280, protein: 8, carbs: 44, fats: 8, fiber: 2, serving_size: '1 cup', serving_grams: 200, category: 'snack', tags: ['fast food'] },
  { id: 'fried-rice-veg', name: 'fried rice veg', aliases: [], calories: 280, protein: 6, carbs: 48, fats: 7, fiber: 2, serving_size: '1 cup', serving_grams: 200, category: 'snack', tags: ['fast food'] },
  { id: 'fried-rice-chicken', name: 'fried rice chicken', aliases: [], calories: 340, protein: 16, carbs: 48, fats: 9, fiber: 2, serving_size: '1 cup', serving_grams: 220, category: 'snack', tags: ['fast food'] },
  { id: 'shawarma-chicken', name: 'shawarma chicken', aliases: [], calories: 420, protein: 24, carbs: 44, fats: 16, fiber: 3, serving_size: '1', serving_grams: 250, category: 'snack', tags: ['fast food'] },
  { id: 'shawarma-paneer', name: 'shawarma paneer', aliases: [], calories: 380, protein: 16, carbs: 46, fats: 16, fiber: 3, serving_size: '1', serving_grams: 250, category: 'snack', tags: ['fast food'] },
  { id: 'banana', name: 'banana', aliases: ['kela'], calories: 105, protein: 1.3, carbs: 27, fats: 0.4, fiber: 2.6, serving_size: '1 medium', serving_grams: 118, category: 'fruit', tags: ['fruit'] },
  { id: 'apple', name: 'apple', aliases: ['seb'], calories: 95, protein: 0.5, carbs: 25, fats: 0.3, fiber: 4.4, serving_size: '1 medium', serving_grams: 182, category: 'fruit', tags: ['fruit'] },
  { id: 'orange', name: 'orange', aliases: ['santra', 'narangi'], calories: 62, protein: 1.2, carbs: 15, fats: 0.2, fiber: 3.1, serving_size: '1 medium', serving_grams: 131, category: 'fruit', tags: ['fruit'] },
  { id: 'mango', name: 'mango', aliases: ['aam'], calories: 107, protein: 1.4, carbs: 28, fats: 0.4, fiber: 3, serving_size: '1 cup', serving_grams: 165, category: 'fruit', tags: ['fruit'] },
  { id: 'papaya', name: 'papaya', aliases: ['papita'], calories: 62, protein: 0.7, carbs: 16, fats: 0.4, fiber: 2.5, serving_size: '1 cup', serving_grams: 145, category: 'fruit', tags: ['fruit'] },
  { id: 'guava', name: 'guava', aliases: ['amrood'], calories: 68, protein: 2.6, carbs: 14, fats: 1, fiber: 5.4, serving_size: '1 medium', serving_grams: 100, category: 'fruit', tags: ['fruit'] },
  { id: 'watermelon', name: 'watermelon', aliases: ['tarbooz'], calories: 46, protein: 0.9, carbs: 11, fats: 0.2, fiber: 0.6, serving_size: '1 cup', serving_grams: 152, category: 'fruit', tags: ['fruit'] },
  { id: 'muskmelon', name: 'muskmelon', aliases: ['kharbooja'], calories: 54, protein: 1.3, carbs: 13, fats: 0.3, fiber: 1.4, serving_size: '1 cup', serving_grams: 160, category: 'fruit', tags: ['fruit'] },
  { id: 'grapes', name: 'grapes', aliases: ['angoor'], calories: 104, protein: 1.1, carbs: 27, fats: 0.2, fiber: 1.4, serving_size: '1 cup', serving_grams: 151, category: 'fruit', tags: ['fruit'] },
  { id: 'pomegranate', name: 'pomegranate', aliases: ['anar'], calories: 144, protein: 3, carbs: 33, fats: 2, fiber: 7, serving_size: '1 cup', serving_grams: 174, category: 'fruit', tags: ['fruit'] },
  { id: 'pineapple', name: 'pineapple', aliases: ['ananas'], calories: 82, protein: 0.9, carbs: 22, fats: 0.2, fiber: 2.3, serving_size: '1 cup', serving_grams: 165, category: 'fruit', tags: ['fruit'] },
  { id: 'chikoo', name: 'chikoo', aliases: ['sapota', 'sapodilla'], calories: 83, protein: 0.4, carbs: 20, fats: 1, fiber: 5, serving_size: '1 medium', serving_grams: 100, category: 'fruit', tags: ['fruit'] },
  { id: 'pear', name: 'pear', aliases: ['nashpati'], calories: 101, protein: 0.6, carbs: 27, fats: 0.2, fiber: 5.5, serving_size: '1 medium', serving_grams: 178, category: 'fruit', tags: ['fruit'] },
  { id: 'strawberry', name: 'strawberry', aliases: [], calories: 49, protein: 1, carbs: 12, fats: 0.5, fiber: 3, serving_size: '1 cup', serving_grams: 152, category: 'fruit', tags: ['fruit'] },
  { id: 'kiwi', name: 'kiwi', aliases: [], calories: 42, protein: 0.8, carbs: 10, fats: 0.4, fiber: 2.1, serving_size: '1 medium', serving_grams: 75, category: 'fruit', tags: ['fruit'] },
  { id: 'dates', name: 'dates', aliases: ['khajoor'], calories: 110, protein: 1, carbs: 30, fats: 0.1, fiber: 3.2, serving_size: '2 pieces', serving_grams: 34, category: 'fruit', tags: ['dry fruit'] },
  { id: 'raisins', name: 'raisins', aliases: ['kishmish'], calories: 42, protein: 0.5, carbs: 11, fats: 0.1, fiber: 0.6, serving_size: '1 tbsp', serving_grams: 13, category: 'fruit', tags: ['dry fruit'] },
  { id: 'almonds', name: 'almonds', aliases: ['badam'], calories: 70, protein: 2.5, carbs: 2.5, fats: 6, fiber: 1.5, serving_size: '10 pieces', serving_grams: 12, category: 'protein', tags: ['nuts'] },
  { id: 'cashews', name: 'cashews', aliases: ['kaju'], calories: 90, protein: 3, carbs: 5, fats: 7, fiber: 0.5, serving_size: '10 pieces', serving_grams: 15, category: 'protein', tags: ['nuts'] },
  { id: 'walnuts', name: 'walnuts', aliases: ['akhrot'], calories: 100, protein: 2.5, carbs: 2, fats: 10, fiber: 1, serving_size: '4 halves', serving_grams: 14, category: 'protein', tags: ['nuts'] },
  { id: 'peanuts', name: 'peanuts', aliases: ['moongphali', 'groundnut'], calories: 55, protein: 2.5, carbs: 2, fats: 4.5, fiber: 0.8, serving_size: '1 tbsp', serving_grams: 9, category: 'protein', tags: ['nuts'] },
  { id: 'pistachios', name: 'pistachios', aliases: ['pista'], calories: 45, protein: 1.6, carbs: 2.2, fats: 3.7, fiber: 0.9, serving_size: '10 pieces', serving_grams: 8, category: 'protein', tags: ['nuts'] },
  { id: 'chia-seeds', name: 'chia seeds', aliases: [], calories: 58, protein: 2, carbs: 5, fats: 3.7, fiber: 4, serving_size: '1 tbsp', serving_grams: 12, category: 'protein', tags: ['seeds'] },
  { id: 'flax-seeds', name: 'flax seeds', aliases: ['alsi'], calories: 55, protein: 1.9, carbs: 3, fats: 4.3, fiber: 2.8, serving_size: '1 tbsp', serving_grams: 10, category: 'protein', tags: ['seeds'] },
  { id: 'sunflower-seeds', name: 'sunflower seeds', aliases: [], calories: 51, protein: 2, carbs: 2, fats: 4.5, fiber: 0.8, serving_size: '1 tbsp', serving_grams: 9, category: 'protein', tags: ['seeds'] },
  { id: 'pumpkin-seeds', name: 'pumpkin seeds', aliases: [], calories: 50, protein: 2.5, carbs: 1.5, fats: 4, fiber: 0.5, serving_size: '1 tbsp', serving_grams: 10, category: 'protein', tags: ['seeds'] },
  { id: 'chai-with-milk', name: 'chai with milk', aliases: ['tea', 'masala chai', 'cutting chai', 'chai', 'chay'], calories: 60, protein: 2, carbs: 8, fats: 2, fiber: 0, serving_size: '1 cup', serving_grams: 150, category: 'beverage', tags: ['tea'] },
  { id: 'black-tea', name: 'black tea', aliases: ['plain tea'], calories: 5, protein: 0, carbs: 1, fats: 0, fiber: 0, serving_size: '1 cup', serving_grams: 150, category: 'beverage', tags: ['tea'] },
  { id: 'green-tea', name: 'green tea', aliases: [], calories: 3, protein: 0, carbs: 0.5, fats: 0, fiber: 0, serving_size: '1 cup', serving_grams: 150, category: 'beverage', tags: ['tea'] },
  { id: 'black-coffee', name: 'black coffee', aliases: ['plain coffee'], calories: 5, protein: 0.3, carbs: 0, fats: 0, fiber: 0, serving_size: '1 cup', serving_grams: 150, category: 'beverage', tags: ['coffee'] },
  { id: 'coffee-with-milk', name: 'coffee with milk', aliases: ['cafe coffee', 'kappi'], calories: 50, protein: 2, carbs: 5, fats: 2, fiber: 0, serving_size: '1 cup', serving_grams: 150, category: 'beverage', tags: ['coffee'] },
  { id: 'filter-coffee', name: 'filter coffee', aliases: ['south indian coffee'], calories: 60, protein: 2, carbs: 6, fats: 2.5, fiber: 0, serving_size: '1 cup', serving_grams: 150, category: 'beverage', tags: ['coffee'] },
  { id: 'cappuccino', name: 'cappuccino', aliases: [], calories: 80, protein: 4, carbs: 8, fats: 3, fiber: 0, serving_size: '1 cup', serving_grams: 180, category: 'beverage', tags: ['coffee'] },
  { id: 'latte', name: 'latte', aliases: [], calories: 120, protein: 6, carbs: 12, fats: 5, fiber: 0, serving_size: '1 cup', serving_grams: 240, category: 'beverage', tags: ['coffee'] },
  { id: 'coconut-water', name: 'coconut water', aliases: ['nariyal pani'], calories: 48, protein: 2, carbs: 9, fats: 0.5, fiber: 3, serving_size: '1 glass', serving_grams: 240, category: 'beverage', tags: ['hydration'] },
  { id: 'nimbu-pani', name: 'nimbu pani', aliases: ['lemon water', 'shikanji'], calories: 40, protein: 0.3, carbs: 10, fats: 0, fiber: 0.1, serving_size: '1 glass', serving_grams: 240, category: 'beverage', tags: ['hydration'] },
  { id: 'jaljeera', name: 'jaljeera', aliases: [], calories: 35, protein: 0.5, carbs: 8, fats: 0, fiber: 0.2, serving_size: '1 glass', serving_grams: 240, category: 'beverage', tags: ['hydration'] },
  { id: 'aam-panna', name: 'aam panna', aliases: [], calories: 80, protein: 0.5, carbs: 20, fats: 0, fiber: 1, serving_size: '1 glass', serving_grams: 240, category: 'beverage', tags: ['fruit'] },
  { id: 'banana-shake', name: 'banana shake', aliases: [], calories: 260, protein: 7, carbs: 44, fats: 6, fiber: 2, serving_size: '1 glass', serving_grams: 300, category: 'beverage', tags: ['milkshake'] },
  { id: 'mango-shake', name: 'mango shake', aliases: ['mango milkshake'], calories: 280, protein: 6, carbs: 52, fats: 6, fiber: 2, serving_size: '1 glass', serving_grams: 300, category: 'beverage', tags: ['milkshake'] },
  { id: 'orange-juice', name: 'orange juice', aliases: [], calories: 112, protein: 1.7, carbs: 26, fats: 0.5, fiber: 0.5, serving_size: '1 glass', serving_grams: 240, category: 'beverage', tags: ['juice'] },
  { id: 'whey-shake-water', name: 'whey protein shake with water', aliases: ['protein shake', 'whey'], calories: 120, protein: 24, carbs: 3, fats: 1.5, fiber: 0, serving_size: '1 scoop', serving_grams: 35, category: 'protein', tags: ['supplement'] },
  { id: 'whey-shake-milk', name: 'whey protein shake with milk', aliases: [], calories: 250, protein: 31, carbs: 13, fats: 8, fiber: 0, serving_size: '1 serving', serving_grams: 280, category: 'protein', tags: ['supplement'] },
  { id: 'mass-gainer-shake', name: 'mass gainer shake', aliases: [], calories: 600, protein: 30, carbs: 100, fats: 8, fiber: 2, serving_size: '1 serving', serving_grams: 150, category: 'protein', tags: ['supplement'] },
  { id: 'gulab-jamun', name: 'gulab jamun', aliases: [], calories: 140, protein: 2, carbs: 22, fats: 5, fiber: 0.3, serving_size: '1 piece', serving_grams: 40, category: 'sweet', tags: ['dessert'] },
  { id: 'rasgulla', name: 'rasgulla', aliases: [], calories: 100, protein: 3, carbs: 18, fats: 2, fiber: 0, serving_size: '1 piece', serving_grams: 45, category: 'sweet', tags: ['dessert'] },
  { id: 'jalebi', name: 'jalebi', aliases: [], calories: 150, protein: 1, carbs: 28, fats: 4, fiber: 0.2, serving_size: '2 pieces', serving_grams: 40, category: 'sweet', tags: ['dessert'] },
  { id: 'ladoo-besan', name: 'ladoo besan', aliases: ['besan ka ladoo'], calories: 180, protein: 3, carbs: 24, fats: 8, fiber: 1, serving_size: '1 piece', serving_grams: 35, category: 'sweet', tags: ['dessert'] },
  { id: 'ladoo-motichoor', name: 'ladoo motichoor', aliases: [], calories: 160, protein: 2, carbs: 24, fats: 7, fiber: 0.5, serving_size: '1 piece', serving_grams: 35, category: 'sweet', tags: ['dessert'] },
  { id: 'barfi-milk', name: 'barfi milk', aliases: ['burfi', 'milk cake'], calories: 130, protein: 3, carbs: 18, fats: 5, fiber: 0, serving_size: '1 piece', serving_grams: 30, category: 'sweet', tags: ['dessert'] },
  { id: 'halwa-suji', name: 'halwa suji', aliases: ['sooji halwa', 'rava halwa'], calories: 300, protein: 5, carbs: 50, fats: 10, fiber: 1, serving_size: '1 cup', serving_grams: 180, category: 'sweet', tags: ['dessert'] },
  { id: 'halwa-gajar', name: 'halwa gajar', aliases: ['carrot halwa', 'gajar ka halwa'], calories: 280, protein: 5, carbs: 44, fats: 10, fiber: 2.5, serving_size: '1 cup', serving_grams: 180, category: 'sweet', tags: ['dessert'] },
  { id: 'kheer', name: 'kheer', aliases: ['rice kheer', 'payasam'], calories: 220, protein: 6, carbs: 34, fats: 7, fiber: 0.3, serving_size: '1 cup', serving_grams: 200, category: 'sweet', tags: ['dessert'] },
  { id: 'kulfi', name: 'kulfi', aliases: [], calories: 120, protein: 3, carbs: 16, fats: 5, fiber: 0, serving_size: '1 piece', serving_grams: 60, category: 'sweet', tags: ['dessert'] },
  { id: 'ice-cream-vanilla', name: 'ice cream vanilla', aliases: [], calories: 140, protein: 2.5, carbs: 17, fats: 7, fiber: 0, serving_size: '1 scoop', serving_grams: 66, category: 'sweet', tags: ['dessert'] },
  { id: 'chocolate-brownie', name: 'chocolate brownie', aliases: [], calories: 230, protein: 3, carbs: 30, fats: 12, fiber: 1.5, serving_size: '1 piece', serving_grams: 60, category: 'sweet', tags: ['dessert'] },
  { id: 'cake-slice', name: 'cake slice', aliases: [], calories: 280, protein: 4, carbs: 40, fats: 12, fiber: 1, serving_size: '1 slice', serving_grams: 80, category: 'sweet', tags: ['dessert'] },
  { id: 'biscuit-parle-g', name: 'biscuit parle g', aliases: [], calories: 120, protein: 1.8, carbs: 20, fats: 4, fiber: 0.3, serving_size: '4 pieces', serving_grams: 28, category: 'sweet', tags: ['snack'] },
  { id: 'chicken-breast-raw', name: 'chicken breast raw', aliases: [], calories: 120, protein: 23, carbs: 0, fats: 2.5, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['chicken'] },
  { id: 'tofu-firm', name: 'tofu firm', aliases: ['bean curd'], calories: 80, protein: 9, carbs: 2, fats: 4, fiber: 0.3, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['soy'] },
  { id: 'paneer-low-fat', name: 'paneer low fat', aliases: [], calories: 180, protein: 20, carbs: 4, fats: 10, fiber: 0, serving_size: '100g', serving_grams: 100, category: 'protein', tags: ['dairy'] },
  { id: 'egg-boiled-3', name: 'egg boiled 3', aliases: ['3 eggs', 'three eggs'], calories: 234, protein: 18, carbs: 1.8, fats: 15, fiber: 0, serving_size: '3 eggs', serving_grams: 150, category: 'protein', tags: ['eggs'] },
  { id: 'egg-boiled-4', name: 'egg boiled 4', aliases: ['4 eggs', 'four eggs'], calories: 312, protein: 24, carbs: 2.4, fats: 20, fiber: 0, serving_size: '4 eggs', serving_grams: 200, category: 'protein', tags: ['eggs'] },
  { id: 'greek-yogurt-high-protein', name: 'greek yogurt high protein', aliases: [], calories: 170, protein: 24, carbs: 10, fats: 0, fiber: 0, serving_size: '1 cup', serving_grams: 200, category: 'protein', tags: ['dairy'] },
];

export const foodById =
  new Map(
    foodDatabase.map(item => [
      item.id,
      item,
    ]),
  );

export const searchableFoods =
  foodDatabase.map(food => ({
    ...food,
    searchableTokens: [
      food.name.toLowerCase(),
      ...food.aliases.map(alias =>
        alias.toLowerCase(),
      ),
      ...food.tags.map(tag =>
        tag.toLowerCase(),
      ),
    ],
  }));